INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (1, 'EC1 4SD', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (2, '70117', 'New Orleans', 'LA', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (3, '48104', 'Ann Arbor', 'MI', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (4, '100', 'Tokyo', 'NULL', 'Japan');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (5, '33007', 'Oviedo', 'Asturias', 'Spain');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (6, '545', 'Osaka', 'NULL', 'Japan');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (7, '3058', 'Melbourne', 'Victoria', 'Australia');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (8, 'M14 GSD', 'Manchester', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (9, 'S-345 67', 'Göteborg', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (10, '5442', 'Sao Paulo', 'NULL', 'Brazil');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (11, '10785', 'Berlin', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (12, '60439', 'Frankfurt', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (13, '27478', 'Cuxhaven', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (14, '48100', 'Ravenna', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (15, '1320', 'Sandvika', 'NULL', 'Norway');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (16, '97101', 'Bend', 'OR', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (17, 'S-123 45', 'Stockholm', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (18, '75004', 'Paris', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (19, '02134', 'Boston', 'MA', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (20, '0512', 'Singapore', 'NULL', 'Singapore');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (21, '2800', 'Lyngby', 'NULL', 'Denmark');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (22, '9999 ZZ', 'Zaandam', 'NULL', 'Netherlands');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (23, '53120', 'Lappeenranta', 'NULL', 'Finland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (24, '2042', 'Sydney', 'NSW', 'Australia');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (25, 'H1J 1C3', 'Montréal', 'Québec', 'Canada');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (26, '84100', 'Salerno', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (27, '71300', 'Montceau', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (28, '74000', 'Annecy', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (29, 'J2S 7S8', 'Ste-Hyacinthe', 'Québec', 'Canada');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (30, '12209', 'Berlin', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (31, '05021', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (32, '05023', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (33, 'WA1 1DP', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (34, 'S-958 22', 'Luleå', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (35, '68306', 'Mannheim', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (36, '67000', 'Strasbourg', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (37, '28023', 'Madrid', 'NULL', 'Spain');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (38, '13008', 'Marseille', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (39, 'T2F 8M4', 'Tsawassen', 'BC', 'Canada');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (40, 'EC2 5NT', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (41, '1010', 'Buenos Aires', 'NULL', 'Argentina');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (42, '05022', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (43, '3012', 'Bern', 'NULL', 'Switzerland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (44, '05432-043', 'Sao Paulo', 'SP', 'Brazil');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (45, 'WX1 6LT', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (46, '52066', 'Aachen', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (47, '44000', 'Nantes', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (48, 'WX3 6FW', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (49, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (50, '05442-030', 'Sao Paulo', 'SP', 'Brazil');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (51, '28034', 'Madrid', 'NULL', 'Spain');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (52, '59000', 'Lille', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (53, 'S-844 67', 'Bräcke', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (54, '80805', 'München', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (55, '44000', 'Nantes', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (56, '10100', 'Torino', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (57, '1675', 'Lisboa', 'NULL', 'Portugal');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (58, '08022', 'Barcelona', 'NULL', 'Spain');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (59, '41101', 'Sevilla', 'NULL', 'Spain');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (60, '04876-786', 'Campinas', 'SP', 'Brazil');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (61, '97403', 'Eugene', 'OR', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (62, '1081', 'Caracas', 'DF', 'Venezuela');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (63, '05454-876', 'Rio de Janeiro', 'RJ', 'Brazil');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (64, '5022', 'San Cristóbal', 'Táchira', 'Venezuela');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (65, '97827', 'Elgin', 'OR', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (66, 'NULL', 'Cork', 'Co. Cork', 'Ireland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (67, 'PO31 7PJ', 'Cowes', 'Isle of Wight', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (68, '14776', 'Brandenburg', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (69, '78000', 'Versailles', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (70, '31000', 'Toulouse', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (71, 'V3F 2K1', 'Vancouver', 'BC', 'Canada');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (72, '99362', 'Walla Walla', 'WA', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (73, '60528', 'Frankfurt a.M.', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (74, '94117', 'San Francisco', 'CA', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (75, '3508', 'Barquisimeto', 'Lara', 'Venezuela');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (76, '4980', 'I. de Margarita', 'Nueva Esparta', 'Venezuela');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (77, '97219', 'Portland', 'OR', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (78, '24100', 'Bergamo', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (79, 'B-1180', 'Bruxelles', 'NULL', 'Belgium');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (80, 'H1J 1C3', 'Montréal', 'Québec', 'Canada');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (81, '04179', 'Leipzig', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (82, 'SW7 1RZ', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (83, '99508', 'Anchorage', 'AK', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (84, '50739', 'Köln', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (85, '75012', 'Paris', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (86, '05033', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (87, '5020', 'Salzburg', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (88, '1756', 'Lisboa', 'NULL', 'Portugal');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (89, '02389-673', 'Rio de Janeiro', 'RJ', 'Brazil');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (90, '05487-020', 'Sao Paulo', 'SP', 'Brazil');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (91, '01307', 'Cunewalde', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (92, '87110', 'Albuquerque', 'NM', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (93, '42100', 'Reggio Emilia', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (94, '02389-890', 'Rio de Janeiro', 'RJ', 'Brazil');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (95, '1203', 'Genève', 'NULL', 'Switzerland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (96, '28001', 'Madrid', 'NULL', 'Spain');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (97, '4110', 'Stavern', 'NULL', 'Norway');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (98, '83720', 'Boise', 'ID', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (99, 'OX15 4NB', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (100, '1734', 'Kobenhavn', 'NULL', 'Denmark');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (101, '75016', 'Paris', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (102, '82520', 'Lander', 'WY', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (103, 'B-6000', 'Charleroi', 'NULL', 'Belgium');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (104, '97201', 'Portland', 'OR', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (105, '59801', 'Butte', 'MT', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (106, '44087', 'Münster', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (107, '05634-030', 'Sao Paulo', 'SP', 'Brazil');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (108, '98034', 'Kirkland', 'WA', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (109, '8200', 'Århus', 'NULL', 'Denmark');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (110, '69004', 'Lyon', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (111, '51100', 'Reims', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (112, '70563', 'Stuttgart', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (113, '90110', 'Oulu', 'NULL', 'Finland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (114, '08737-363', 'Resende', 'SP', 'Brazil');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (115, '98128', 'Seattle', 'WA', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (116, '21240', 'Helsinki', 'NULL', 'Finland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (117, '01-012', 'Warszawa', 'NULL', 'Poland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (118, '98401', 'Tacoma', 'WA', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (119, '98033', 'Kirkland', 'WA', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (120, '98052', 'Redmond', 'WA', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (121, 'EC2 7JR', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (122, 'RG1 9SP', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (123, '98105', 'Seattle', 'WA', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (124, 'WG2 7LT', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (125, '98122', 'Seattle', 'WA', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (126, '51100', 'Reims', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (127, '44087', 'Münster', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (128, '69004', 'Lyon', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (129, 'B-6000', 'Charleroi', 'NULL', 'Belgium');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (130, '3012', 'Bern', 'NULL', 'Switzerland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (131, '1204', 'Genève', 'NULL', 'Switzerland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (132, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (133, '05022', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (134, '50739', 'Köln', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (135, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (136, 'S-844 67', 'Bräcke', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (137, '67000', 'Strasbourg', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (138, '90110', 'Oulu', 'NULL', 'Finland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (139, '80805', 'München', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (140, '98124', 'Seattle', 'WA', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (141, '90110', 'Oulu', 'NULL', 'Finland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (142, '01307', 'Cunewalde', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (143, '51100', 'Reims', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (144, '24100', 'Bergamo', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (145, '05033', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (146, '04179', 'Leipzig', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (147, 'S-958 22', 'Luleå', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (148, '60528', 'Frankfurt a.M.', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (149, 'S-958 22', 'Luleå', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (150, '28001', 'Madrid', 'NULL', 'Spain');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (151, '28001', 'Madrid', 'NULL', 'Spain');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (152, '60528', 'Frankfurt a.M.', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (153, '01307', 'Cunewalde', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (154, '01307', 'Cunewalde', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (155, '42100', 'Reggio Emilia', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (156, 'EC2 5NT', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (157, '05033', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (158, '51100', 'Reims', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (159, '67000', 'Strasbourg', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (160, 'NULL', 'Cork', 'Co. Cork', 'Ireland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (161, '24100', 'Bergamo', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (162, '70563', 'Stuttgart', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (163, 'B-6000', 'Charleroi', 'NULL', 'Belgium');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (164, '41101', 'Sevilla', 'NULL', 'Spain');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (165, '05033', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (166, '28001', 'Madrid', 'NULL', 'Spain');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (167, '05021', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (168, 'NULL', 'Cork', 'Co. Cork', 'Ireland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (169, '44000', 'Nantes', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (170, '70563', 'Stuttgart', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (171, '01307', 'Cunewalde', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (172, '05033', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (173, '90110', 'Oulu', 'NULL', 'Finland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (174, '05033', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (175, '14776', 'Brandenburg', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (176, '14776', 'Brandenburg', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (177, '28023', 'Madrid', 'NULL', 'Spain');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (178, 'S-844 67', 'Bräcke', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (179, '1675', 'Lisboa', 'NULL', 'Portugal');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (180, '13008', 'Marseille', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (181, '90110', 'Oulu', 'NULL', 'Finland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (182, '69004', 'Lyon', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (183, 'NULL', 'Cork', 'Co. Cork', 'Ireland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (184, '1756', 'Lisboa', 'NULL', 'Portugal');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (185, '80805', 'München', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (186, '13008', 'Marseille', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (187, '1734', 'Kobenhavn', 'NULL', 'Denmark');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (188, '80805', 'München', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (189, '60528', 'Frankfurt a.M.', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (190, '98124', 'Seattle', 'WA', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (191, '01307', 'Cunewalde', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (192, '70563', 'Stuttgart', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (193, '31000', 'Toulouse', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (194, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (195, '1675', 'Lisboa', 'NULL', 'Portugal');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (196, '5020', 'Salzburg', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (197, '05033', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (198, 'CO7 6JX', 'Colchester', 'Essex', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (199, '70563', 'Stuttgart', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (200, '31000', 'Toulouse', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (201, 'OX15 4NB', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (202, '67000', 'Strasbourg', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (203, '01307', 'Cunewalde', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (204, '13008', 'Marseille', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (205, '52066', 'Aachen', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (206, 'WX3 6FW', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (207, '05023', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (208, '8022', 'Barcelona', 'NULL', 'Spain');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (209, '8200', 'Århus', 'NULL', 'Denmark');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (210, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (211, '3012', 'Bern', 'NULL', 'Switzerland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (212, '31000', 'Toulouse', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (213, 'NULL', 'Cork', 'Co. Cork', 'Ireland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (214, '01-012', 'Warszawa', 'NULL', 'Poland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (215, 'OX15 4NB', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (216, 'S-844 67', 'Bräcke', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (217, 'NULL', 'Cork', 'Co. Cork', 'Ireland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (218, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (219, 'CO7 6JX', 'Colchester', 'Essex', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (220, 'S-958 22', 'Luleå', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (221, '4110', 'Stavern', 'NULL', 'Norway');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (222, 'OX15 4NB', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (223, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (224, '52066', 'Aachen', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (225, '5020', 'Salzburg', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (226, '80805', 'München', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (227, '1756', 'Lisboa', 'NULL', 'Portugal');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (228, '8200', 'Århus', 'NULL', 'Denmark');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (229, 'WX3 6FW', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (230, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (231, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (232, '24100', 'Bergamo', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (233, '50739', 'Köln', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (234, '59000', 'Lille', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (235, '1010', 'Buenos Aires', 'NULL', 'Argentina');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (236, '90110', 'Oulu', 'NULL', 'Finland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (237, '31000', 'Toulouse', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (238, '90110', 'Oulu', 'NULL', 'Finland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (239, '1734', 'Kobenhavn', 'NULL', 'Denmark');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (240, '01307', 'Cunewalde', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (241, '1204', 'Genève', 'NULL', 'Switzerland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (242, '10100', 'Torino', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (243, '31000', 'Toulouse', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (244, '8022', 'Barcelona', 'NULL', 'Spain');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (245, '5020', 'Salzburg', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (246, '42100', 'Reggio Emilia', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (247, 'NULL', 'Cork', 'Co. Cork', 'Ireland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (248, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (249, '1756', 'Lisboa', 'NULL', 'Portugal');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (250, 'S-844 67', 'Bräcke', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (251, 'WX1 6LT', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (252, '67000', 'Strasbourg', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (253, '90110', 'Oulu', 'NULL', 'Finland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (254, '44087', 'Münster', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (255, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (256, '42100', 'Reggio Emilia', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (257, 'S-958 22', 'Luleå', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (258, 'S-958 22', 'Luleå', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (259, '44087', 'Münster', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (260, '1010', 'Buenos Aires', 'NULL', 'Argentina');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (261, '67000', 'Strasbourg', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (262, '69004', 'Lyon', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (263, '01307', 'Cunewalde', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (264, 'CO7 6JX', 'Colchester', 'Essex', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (265, '31000', 'Toulouse', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (266, '90110', 'Oulu', 'NULL', 'Finland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (267, '14776', 'Brandenburg', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (268, '14776', 'Brandenburg', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (269, 'B-6000', 'Charleroi', 'NULL', 'Belgium');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (270, '69004', 'Lyon', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (271, 'S-844 67', 'Bräcke', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (272, 'WX1 6LT', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (273, 'B-6000', 'Charleroi', 'NULL', 'Belgium');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (274, '1675', 'Lisboa', 'NULL', 'Portugal');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (275, '8200', 'Århus', 'NULL', 'Denmark');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (276, '24100', 'Bergamo', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (277, '14776', 'Brandenburg', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (278, '98124', 'Seattle', 'WA', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (279, '13008', 'Marseille', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (280, 'EC2 5NT', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (281, 'OX15 4NB', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (282, '05033', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (283, 'B-6000', 'Charleroi', 'NULL', 'Belgium');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (284, '1756', 'Lisboa', 'NULL', 'Portugal');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (285, '69004', 'Lyon', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (286, '59000', 'Lille', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (287, '98124', 'Seattle', 'WA', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (288, 'EC2 5NT', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (289, '80805', 'München', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (290, '5020', 'Salzburg', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (291, '1675', 'Lisboa', 'NULL', 'Portugal');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (292, '31000', 'Toulouse', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (293, '60528', 'Frankfurt a.M.', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (294, '31000', 'Toulouse', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (295, '68306', 'Mannheim', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (296, '05033', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (297, 'NULL', 'Cork', 'Co. Cork', 'Ireland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (298, '98124', 'Seattle', 'WA', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (299, '14776', 'Brandenburg', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (300, '05023', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (301, '50739', 'Köln', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (302, '68306', 'Mannheim', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (303, '13008', 'Marseille', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (304, '70563', 'Stuttgart', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (305, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (306, '01307', 'Cunewalde', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (307, 'NULL', 'Cork', 'Co. Cork', 'Ireland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (308, 'SW7 1RZ', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (309, '05033', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (310, '3012', 'Bern', 'NULL', 'Switzerland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (311, '4110', 'Stavern', 'NULL', 'Norway');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (312, '1010', 'Buenos Aires', 'NULL', 'Argentina');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (313, '60528', 'Frankfurt a.M.', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (314, 'OX15 4NB', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (315, 'S-958 22', 'Luleå', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (316, '13008', 'Marseille', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (317, '90110', 'Oulu', 'NULL', 'Finland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (318, '01307', 'Cunewalde', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (319, 'B-1180', 'Bruxelles', 'NULL', 'Belgium');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (320, '5020', 'Salzburg', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (321, '1010', 'Buenos Aires', 'NULL', 'Argentina');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (322, 'WX3 6FW', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (323, 'S-844 67', 'Bräcke', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (324, '60528', 'Frankfurt a.M.', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (325, '05023', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (326, '60528', 'Frankfurt a.M.', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (327, '1204', 'Genève', 'NULL', 'Switzerland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (328, 'EC2 5NT', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (329, 'EC2 5NT', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (330, '01307', 'Cunewalde', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (331, '14776', 'Brandenburg', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (332, '69004', 'Lyon', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (333, 'OX15 4NB', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (334, '44087', 'Münster', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (335, '01307', 'Cunewalde', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (336, '41101', 'Sevilla', 'NULL', 'Spain');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (337, '1675', 'Lisboa', 'NULL', 'Portugal');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (338, '90110', 'Oulu', 'NULL', 'Finland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (339, '50739', 'Köln', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (340, '1734', 'Kobenhavn', 'NULL', 'Denmark');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (341, '60528', 'Frankfurt a.M.', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (342, 'CO7 6JX', 'Colchester', 'Essex', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (343, '67000', 'Strasbourg', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (344, '80805', 'München', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (345, 'S-844 67', 'Bräcke', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (346, '42100', 'Reggio Emilia', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (347, '67000', 'Strasbourg', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (348, 'NULL', 'Cork', 'Co. Cork', 'Ireland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (349, '8022', 'Barcelona', 'NULL', 'Spain');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (350, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (351, 'S-958 22', 'Luleå', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (352, '05023', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (353, '04179', 'Leipzig', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (354, '05033', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (355, 'EC2 5NT', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (356, '50739', 'Köln', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (357, '68306', 'Mannheim', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (358, '90110', 'Oulu', 'NULL', 'Finland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (359, '67000', 'Strasbourg', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (360, '42100', 'Reggio Emilia', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (361, '01307', 'Cunewalde', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (362, '8200', 'Århus', 'NULL', 'Denmark');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (363, '60528', 'Frankfurt a.M.', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (364, '60528', 'Frankfurt a.M.', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (365, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (366, '98124', 'Seattle', 'WA', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (367, '5020', 'Salzburg', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (368, 'EC2 5NT', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (369, '8200', 'Århus', 'NULL', 'Denmark');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (370, '1675', 'Lisboa', 'NULL', 'Portugal');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (371, '44087', 'Münster', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (372, '44000', 'Nantes', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (373, '31000', 'Toulouse', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (374, '01-012', 'Warszawa', 'NULL', 'Poland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (375, '68306', 'Mannheim', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (376, '21240', 'Helsinki', 'NULL', 'Finland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (377, '80805', 'München', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (378, '05021', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (379, 'S-958 22', 'Luleå', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (380, '67000', 'Strasbourg', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (381, '41101', 'Sevilla', 'NULL', 'Spain');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (382, '14776', 'Brandenburg', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (383, '31000', 'Toulouse', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (384, '70563', 'Stuttgart', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (385, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (386, '59000', 'Lille', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (387, '24100', 'Bergamo', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (388, '90110', 'Oulu', 'NULL', 'Finland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (389, '4110', 'Stavern', 'NULL', 'Norway');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (390, '70563', 'Stuttgart', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (391, '1734', 'Kobenhavn', 'NULL', 'Denmark');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (392, '12209', 'Berlin', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (393, 'NULL', 'Cork', 'Co. Cork', 'Ireland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (394, 'B-1180', 'Bruxelles', 'NULL', 'Belgium');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (395, '70563', 'Stuttgart', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (396, '80805', 'München', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (397, 'S-958 22', 'Luleå', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (398, '42100', 'Reggio Emilia', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (399, '01307', 'Cunewalde', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (400, 'NULL', 'Cork', 'Co. Cork', 'Ireland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (401, '13008', 'Marseille', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (402, '1675', 'Lisboa', 'NULL', 'Portugal');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (403, '1204', 'Genève', 'NULL', 'Switzerland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (404, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (405, '70563', 'Stuttgart', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (406, '1734', 'Kobenhavn', 'NULL', 'Denmark');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (407, '80805', 'München', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (408, '44000', 'Nantes', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (409, 'S-958 22', 'Luleå', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (410, '21240', 'Helsinki', 'NULL', 'Finland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (411, '80805', 'München', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (412, '05033', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (413, '05023', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (414, '67000', 'Strasbourg', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (415, '05023', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (416, '44000', 'Nantes', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (417, '50739', 'Köln', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (418, '5020', 'Salzburg', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (419, 'NULL', 'Cork', 'Co. Cork', 'Ireland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (420, '8200', 'Århus', 'NULL', 'Denmark');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (421, 'S-958 22', 'Luleå', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (422, '01307', 'Cunewalde', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (423, '12209', 'Berlin', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (424, '98124', 'Seattle', 'WA', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (425, '01307', 'Cunewalde', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (426, '21240', 'Helsinki', 'NULL', 'Finland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (427, '98124', 'Seattle', 'WA', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (428, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (429, '04179', 'Leipzig', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (430, 'NULL', 'Cork', 'Co. Cork', 'Ireland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (431, '12209', 'Berlin', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (432, 'S-844 67', 'Bräcke', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (433, 'CO7 6JX', 'Colchester', 'Essex', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (434, '10100', 'Torino', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (435, 'NULL', 'Cork', 'Co. Cork', 'Ireland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (436, '13008', 'Marseille', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (437, '1010', 'Buenos Aires', 'NULL', 'Argentina');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (438, '80805', 'München', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (439, '14776', 'Brandenburg', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (440, '01307', 'Cunewalde', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (441, '98124', 'Seattle', 'WA', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (442, 'WX3 6FW', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (443, '42100', 'Reggio Emilia', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (444, '13008', 'Marseille', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (445, '3012', 'Bern', 'NULL', 'Switzerland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (446, '13008', 'Marseille', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (447, 'S-958 22', 'Luleå', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (448, 'NULL', 'Cork', 'Co. Cork', 'Ireland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (449, '51100', 'Reims', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (450, '75016', 'Paris', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (451, '51100', 'Reims', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (452, '98124', 'Seattle', 'WA', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (453, 'CO7 6JX', 'Colchester', 'Essex', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (454, 'CO7 6JX', 'Colchester', 'Essex', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (455, '8200', 'Århus', 'NULL', 'Denmark');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (456, '01307', 'Cunewalde', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (457, '3012', 'Bern', 'NULL', 'Switzerland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (458, '5020', 'Salzburg', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (459, '90110', 'Oulu', 'NULL', 'Finland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (460, '1204', 'Genève', 'NULL', 'Switzerland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (461, 'SW7 1RZ', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (462, '10100', 'Torino', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (463, '24100', 'Bergamo', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (464, '13008', 'Marseille', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (465, '1204', 'Genève', 'NULL', 'Switzerland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (466, '05021', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (467, 'B-1180', 'Bruxelles', 'NULL', 'Belgium');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (468, 'S-844 67', 'Bräcke', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (469, '59000', 'Lille', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (470, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (471, '01307', 'Cunewalde', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (472, '50739', 'Köln', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (473, 'B-6000', 'Charleroi', 'NULL', 'Belgium');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (474, 'CO7 6JX', 'Colchester', 'Essex', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (475, '8200', 'Århus', 'NULL', 'Denmark');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (476, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (477, '60528', 'Frankfurt a.M.', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (478, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (479, 'S-844 67', 'Bräcke', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (480, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (481, 'S-958 22', 'Luleå', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (482, '04179', 'Leipzig', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (483, '90110', 'Oulu', 'NULL', 'Finland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (484, '1010', 'Buenos Aires', 'NULL', 'Argentina');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (485, '24100', 'Bergamo', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (486, '31000', 'Toulouse', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (487, '01307', 'Cunewalde', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (488, '59000', 'Lille', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (489, '80805', 'München', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (490, '01-012', 'Warszawa', 'NULL', 'Poland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (491, 'CO7 6JX', 'Colchester', 'Essex', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (492, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (493, '52066', 'Aachen', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (494, '14776', 'Brandenburg', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (495, 'OX15 4NB', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (496, '28023', 'Madrid', 'NULL', 'Spain');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (497, '1734', 'Kobenhavn', 'NULL', 'Denmark');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (498, 'OX15 4NB', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (499, '69004', 'Lyon', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (500, '10100', 'Torino', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (501, '42100', 'Reggio Emilia', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (502, '69004', 'Lyon', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (503, '14776', 'Brandenburg', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (504, '24100', 'Bergamo', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (505, '1010', 'Buenos Aires', 'NULL', 'Argentina');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (506, 'S-844 67', 'Bräcke', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (507, '52066', 'Aachen', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (508, '67000', 'Strasbourg', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (509, '13008', 'Marseille', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (510, '1010', 'Buenos Aires', 'NULL', 'Argentina');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (511, '4110', 'Stavern', 'NULL', 'Norway');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (512, '31000', 'Toulouse', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (513, '50739', 'Köln', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (514, '12209', 'Berlin', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (515, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (516, 'S-958 22', 'Luleå', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (517, 'B-6000', 'Charleroi', 'NULL', 'Belgium');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (518, '05033', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (519, '69004', 'Lyon', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (520, '5020', 'Salzburg', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (521, '01307', 'Cunewalde', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (522, 'B-6000', 'Charleroi', 'NULL', 'Belgium');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (523, 'WX1 6LT', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (524, '14776', 'Brandenburg', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (525, '69004', 'Lyon', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (526, '68306', 'Mannheim', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (527, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (528, '05023', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (529, 'S-958 22', 'Luleå', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (530, '78000', 'Versailles', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (531, '80805', 'München', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (532, '44000', 'Nantes', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (533, '98124', 'Seattle', 'WA', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (534, '60528', 'Frankfurt a.M.', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (535, 'CO7 6JX', 'Colchester', 'Essex', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (536, '01307', 'Cunewalde', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (537, 'S-958 22', 'Luleå', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (538, 'OX15 4NB', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (539, '01-012', 'Warszawa', 'NULL', 'Poland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (540, '13008', 'Marseille', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (541, '41101', 'Sevilla', 'NULL', 'Spain');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (542, '21240', 'Helsinki', 'NULL', 'Finland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (543, '41101', 'Sevilla', 'NULL', 'Spain');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (544, 'S-958 22', 'Luleå', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (545, '13008', 'Marseille', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (546, '01307', 'Cunewalde', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (547, '21240', 'Helsinki', 'NULL', 'Finland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (548, 'S-844 67', 'Bräcke', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (549, '1010', 'Buenos Aires', 'NULL', 'Argentina');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (550, 'B-6000', 'Charleroi', 'NULL', 'Belgium');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (551, '8022', 'Barcelona', 'NULL', 'Spain');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (552, '41101', 'Sevilla', 'NULL', 'Spain');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (553, '44000', 'Nantes', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (554, '60528', 'Frankfurt a.M.', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (555, 'B-1180', 'Bruxelles', 'NULL', 'Belgium');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (556, '14776', 'Brandenburg', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (557, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (558, 'B-1180', 'Bruxelles', 'NULL', 'Belgium');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (559, 'NULL', 'Cork', 'Co. Cork', 'Ireland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (560, '1010', 'Buenos Aires', 'NULL', 'Argentina');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (561, 'S-844 67', 'Bräcke', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (562, '98124', 'Seattle', 'WA', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (563, '01-012', 'Warszawa', 'NULL', 'Poland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (564, '75016', 'Paris', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (565, '42100', 'Reggio Emilia', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (566, '4110', 'Stavern', 'NULL', 'Norway');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (567, '21240', 'Helsinki', 'NULL', 'Finland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (568, '41101', 'Sevilla', 'NULL', 'Spain');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (569, 'NULL', 'Cork', 'Co. Cork', 'Ireland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (570, '05033', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (571, '1010', 'Buenos Aires', 'NULL', 'Argentina');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (572, '28001', 'Madrid', 'NULL', 'Spain');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (573, 'CO7 6JX', 'Colchester', 'Essex', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (574, '8200', 'Århus', 'NULL', 'Denmark');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (575, '31000', 'Toulouse', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (576, 'S-958 22', 'Luleå', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (577, '05021', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (578, '78000', 'Versailles', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (579, '8022', 'Barcelona', 'NULL', 'Spain');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (580, '80805', 'München', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (581, 'B-6000', 'Charleroi', 'NULL', 'Belgium');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (582, '1204', 'Genève', 'NULL', 'Switzerland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (583, '13008', 'Marseille', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (584, '60528', 'Frankfurt a.M.', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (585, '1010', 'Buenos Aires', 'NULL', 'Argentina');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (586, '01307', 'Cunewalde', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (587, '24100', 'Bergamo', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (588, '13008', 'Marseille', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (589, '42100', 'Reggio Emilia', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (590, 'EC2 5NT', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (591, '04179', 'Leipzig', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (592, '8200', 'Århus', 'NULL', 'Denmark');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (593, 'EC2 5NT', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (594, '41101', 'Sevilla', 'NULL', 'Spain');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (595, '24100', 'Bergamo', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (596, '1204', 'Genève', 'NULL', 'Switzerland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (597, '12209', 'Berlin', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (598, 'CO7 6JX', 'Colchester', 'Essex', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (599, 'S-844 67', 'Bräcke', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (600, '68306', 'Mannheim', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (601, '1010', 'Buenos Aires', 'NULL', 'Argentina');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (602, '01307', 'Cunewalde', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (603, '1675', 'Lisboa', 'NULL', 'Portugal');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (604, '75016', 'Paris', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (605, '3012', 'Bern', 'NULL', 'Switzerland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (606, '44087', 'Münster', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (607, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (608, '28023', 'Madrid', 'NULL', 'Spain');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (609, '44000', 'Nantes', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (610, '78000', 'Versailles', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (611, '78000', 'Versailles', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (612, 'S-844 67', 'Bräcke', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (613, 'B-1180', 'Bruxelles', 'NULL', 'Belgium');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (614, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (615, 'S-844 67', 'Bräcke', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (616, 'NULL', 'Cork', 'Co. Cork', 'Ireland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (617, '1010', 'Buenos Aires', 'NULL', 'Argentina');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (618, 'WX3 6FW', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (619, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (620, '01307', 'Cunewalde', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (621, 'S-844 67', 'Bräcke', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (622, '8200', 'Århus', 'NULL', 'Denmark');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (623, '05033', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (624, '01307', 'Cunewalde', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (625, '01-012', 'Warszawa', 'NULL', 'Poland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (626, '50739', 'Köln', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (627, 'S-844 67', 'Bräcke', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (628, 'B-1180', 'Bruxelles', 'NULL', 'Belgium');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (629, '21240', 'Helsinki', 'NULL', 'Finland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (630, '1756', 'Lisboa', 'NULL', 'Portugal');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (631, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (632, '41101', 'Sevilla', 'NULL', 'Spain');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (633, '42100', 'Reggio Emilia', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (634, '12209', 'Berlin', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (635, '80805', 'München', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (636, '28001', 'Madrid', 'NULL', 'Spain');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (637, '4110', 'Stavern', 'NULL', 'Norway');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (638, 'CO7 6JX', 'Colchester', 'Essex', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (639, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (640, '1010', 'Buenos Aires', 'NULL', 'Argentina');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (641, '50739', 'Köln', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (642, '01307', 'Cunewalde', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (643, 'EC2 5NT', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (644, 'WX3 6FW', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (645, '90110', 'Oulu', 'NULL', 'Finland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (646, '10100', 'Torino', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (647, '14776', 'Brandenburg', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (648, '3012', 'Bern', 'NULL', 'Switzerland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (649, '98124', 'Seattle', 'WA', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (650, '1204', 'Genève', 'NULL', 'Switzerland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (651, 'B-6000', 'Charleroi', 'NULL', 'Belgium');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (652, '52066', 'Aachen', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (653, '41101', 'Sevilla', 'NULL', 'Spain');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (654, 'B-6000', 'Charleroi', 'NULL', 'Belgium');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (655, '3012', 'Bern', 'NULL', 'Switzerland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (656, '75016', 'Paris', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (657, '01-012', 'Warszawa', 'NULL', 'Poland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (658, '70563', 'Stuttgart', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (659, 'WX3 6FW', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (660, 'S-844 67', 'Bräcke', 'NULL', 'Sweden');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (661, '31000', 'Toulouse', 'NULL', 'France');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (662, '5020', 'Salzburg', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (663, '1010', 'Buenos Aires', 'NULL', 'Argentina');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (664, 'WX3 6FW', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (665, 'SW7 1RZ', 'London', 'NULL', 'UK');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (666, '68306', 'Mannheim', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (667, '10100', 'Torino', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (668, '42100', 'Reggio Emilia', 'NULL', 'Italy');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (669, 'NULL', 'Cork', 'Co. Cork', 'Ireland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (670, '98124', 'Seattle', 'WA', 'USA');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (671, '52066', 'Aachen', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (672, '05033', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (673, '60528', 'Frankfurt a.M.', 'NULL', 'Germany');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (674, '8010', 'Graz', 'NULL', 'Austria');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (675, '05033', 'México D.F.', 'NULL', 'Mexico');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (676, '1734', 'Kobenhavn', 'NULL', 'Denmark');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (677, '1204', 'Genève', 'NULL', 'Switzerland');
INSERT INTO public."locations_Dim" (location_key, postal_code, city, region, country) VALUES (678, '13008', 'Marseille', 'NULL', 'France');